chore(deps): bump org.springframework:spring-context from 6.1.14 to 6.1.20 in /clients/java-logger/grpc-test-app in the maven group across 1 directory (#508)
Bumps the maven group with 1 update in the
/clients/java-logger/grpc-test-app directory:
[org.springframework:spring-context](https://github.com/spring-projects/spring-framework).

Updates `org.springframework:spring-context` from 6.1.14 to 6.1.20
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/spring-projects/spring-framework/releases">org.springframework:spring-context's
releases</a>.</em></p>
<blockquote>
<h2>v6.1.20</h2>
<h2>:star: New Features</h2>
<ul>
<li>Add option for case-insensitive match to PatternMatchUtils <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/34802">#34802</a></li>
</ul>
<h2>:lady_beetle: Bug Fixes</h2>
<ul>
<li>HttpComponentsClientHttpRequestFactory setConnectionRequestTimeout
not working with httpclient 5.3.1 <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/34854">#34854</a></li>
<li>Accidental ClassLoader defineClass enforcement after <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/34677">#34677</a>
<a
href="https://redirect.github.com/spring-projects/spring-framework/issues/34839">#34839</a></li>
</ul>
<h2>:notebook_with_decorative_cover: Documentation</h2>
<ul>
<li>Clarify <code>CompositePropertySource</code> behavior for
<code>EnumerablePropertySource</code> contract <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/34887">#34887</a></li>
</ul>
<h2>:hammer: Dependency Upgrades</h2>
<ul>
<li>Upgrade to Reactor 2023.0.18 <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/34899">#34899</a></li>
</ul>
<h2>v6.1.19</h2>
<h2>:star: New Features</h2>
<ul>
<li>Suggest compilation with <code>-parameters</code> when
<code>AspectJAdviceParameterNameDiscoverer</code> fails against
ambiguity <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/34618">#34618</a></li>
</ul>
<h2>:lady_beetle: Bug Fixes</h2>
<ul>
<li><code>PropertyBatchUpdateException</code>: causes of nested
<code>PropertyAccessException</code>s not shown in output <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/34698">#34698</a></li>
<li>Change in Jar usecache behavior with Spring 6.1.x causing
java.lang.IllegalStateException: zip file closed <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/34694">#34694</a></li>
<li>Startup performance regression due to CGLIB class load attempts in
Spring 6.1.x <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/34693">#34693</a></li>
<li>IllegalAccessError for package-private member of
AzureStorageConfiguration on WebSphere <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/34690">#34690</a></li>
<li><code>@Configuration</code> classes can no longer be
<code>abstract</code> without <code>@Bean</code> methods <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/34689">#34689</a></li>
<li>Generated-code for LinkedHashMap is missing static keyword <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/34661">#34661</a></li>
<li>AbstractReactiveTransactionManager throws IllegalStateException when
rollback fails after commit attempt <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/34619">#34619</a></li>
</ul>
<h2>:notebook_with_decorative_cover: Documentation</h2>
<ul>
<li>Add javadoc notes on potential exception suppression in
<code>ListableBeanFactory#getBeansOfType</code> <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/34631">#34631</a></li>
<li>Remove remaining references to Forwarded headers in
MvcUriComponentsBuilder <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/34626">#34626</a></li>
<li><code>MvcUriComponentsBuilder</code> javadocs inaccurately reflects
usage of forwarded headers <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/34620">#34620</a></li>
</ul>
<h2>v6.1.18</h2>
<h2>:star: New Features</h2>
<ul>
<li>Avoid unnecessary CGLIB processing on configuration classes <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/34487">#34487</a></li>
<li>Inconsistent default class loaders in hint classes <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/34473">#34473</a></li>
</ul>
<h2>:lady_beetle: Bug Fixes</h2>
<ul>
<li>DefaultManagedTaskExecutor throws
java.lang.UnsupportedOperationException: isShutdown when rejecting tasks
<a
href="https://redirect.github.com/spring-projects/spring-framework/issues/34515">#34515</a></li>
<li>Endless loop with DataSourceUtils in spring-jdbc <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/34497">#34497</a></li>
<li>MockHttpServletResponse - handle multiple values for
Content-Language header <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/34491">#34491</a></li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/spring-projects/spring-framework/commit/1f9c59b17b5a7afc69f28b694de4553d6b65c9d5"><code>1f9c59b</code></a>
Release v6.1.20</li>
<li><a
href="https://github.com/spring-projects/spring-framework/commit/edfcc6ffb188e4614ec9b212e3208b666981851c"><code>edfcc6f</code></a>
Make use of PatternMatchUtils ignoreCase option</li>
<li><a
href="https://github.com/spring-projects/spring-framework/commit/f93132b11ef6aa5718d20a05846828659c082fe8"><code>f93132b</code></a>
Add missing <a href="https://github.com/since"><code>@​since</code></a>
tags in PatternMatchUtils</li>
<li><a
href="https://github.com/spring-projects/spring-framework/commit/6ab4c84bd528d9480071d3dec4ff0b4904dbbb2f"><code>6ab4c84</code></a>
Upgrade to Reactor 2023.0.18</li>
<li><a
href="https://github.com/spring-projects/spring-framework/commit/d5fca0d2c5d96b1a59a5814aa38c5f3b15238301"><code>d5fca0d</code></a>
Upgrade to Jetty 12.0.21, Netty 4.1.121, Apache HttpClient 5.4.4,
Checkstyle ...</li>
<li><a
href="https://github.com/spring-projects/spring-framework/commit/cbb94193fe9f11d1af8b8958292b0edc8451cd4c"><code>cbb9419</code></a>
Clarify CompositePropertySource behavior for EnumerablePropertySource
contract</li>
<li><a
href="https://github.com/spring-projects/spring-framework/commit/5b5e2b68767537f204d8392201497805ce6562d7"><code>5b5e2b6</code></a>
Fix HttpClient 5.3.x request config compatibility</li>
<li><a
href="https://github.com/spring-projects/spring-framework/commit/a5b0399a1d6f3e89ae3bbfeb0b13142ecaddb4e9"><code>a5b0399</code></a>
Polishing</li>
<li><a
href="https://github.com/spring-projects/spring-framework/commit/71f27256381d72170f9c6d38eea3032ceb24f030"><code>71f2725</code></a>
Try loadClass on LinkageError in case of same ClassLoader as well</li>
<li><a
href="https://github.com/spring-projects/spring-framework/commit/daee9f1242264215876e67f6ef43b117195385c6"><code>daee9f1</code></a>
Reinstate the @⁠Inject Technology Compatibility Kit (TCK)</li>
<li>Additional commits viewable in <a
href="https://github.com/spring-projects/spring-framework/compare/v6.1.14...v6.1.20">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.springframework:spring-context&package-manager=maven&previous-version=6.1.14&new-version=6.1.20)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions
You can disable automated security fix PRs for this repo from the
[Security Alerts
page](https://github.com/abcxyz/lumberjack/network/alerts).

</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>